### ISSUE TITLE
Add to awesome-ada

### ISSUE THREAD

**Issue by ohenley** [briot/adafuzzy#1]
hi,

In which section of the awesome-ada page would you add this project?

Thx!

**Comment by briot** [comment]
Yes, this project is ready for use, though likely of limited interest. Dmitry Kasakov has a more extensive fuzzy-logic package, though last time I looked it did not have support for fuzzy inference itself.

**Comment by ohenley** [comment]
done

1. Added ada-fuzzy to Libraries/System Modeling
2. Added ada-promises to Libraries/Patterns
3. Added gnatbdd alongside Aunit

Good with you? Thx.
